spring:
  application:
    name: config-bus-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gpqhl0071/config.git
          force-pull: true
          default-label: main
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#          强制拉取职权文件
#          search-paths: abc, def*
#          username:
#          password:

server:
  port: 60002

#  使用
# http://localhost:60000/config-consumer-dev.properties
# http://localhost:60000/config-consumer-dev.yml
# http://localhost:60000/config-consumer/dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always